name: 🤔 Design Proposal
description: Collaborate on a design for a feature/fix or other change
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Summary
      description: 1-2 sentences. Say what this is about.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation and goals
      description: 1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?
    validations:
      required: true
  - type: textarea
    attributes:
      label: In scope
      description: A list of major scenarios, perhaps in priority order.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Out of scope
      description: Scenarios you explicitly want to exclude.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Risks / unknowns
      description: How might others misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Examples
      description: |
        Give brief examples of possible developer and user experiences.

        Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks or applications.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Detailed design
      description: |
        It's often best not to fill this out until you get basic consensus about the above. When you do, consider adding an implementation proposal with the following headings:

        Detailed design
        Drawbacks
        Considered alternatives
        Open questions
        References

        If there's one clear design you have consensus on, you could do that directly in a PR.
    validations:
      required: false
