name: Build Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-code:
    name: Build Code
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: zyactions/dotnet-setup@v1
        with:
          global-json-file: global.json

      - name: Restore .NET dependencies
        uses: zyactions/dotnet-restore@v1

      - name: Build solution
        run: dotnet build
