name: Scan Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '22 7 * * 1'

jobs:
  scan-code:
    name: Scan Code
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Set up .NET
        uses: zyactions/dotnet-setup@v1
        with:
          global-json-file: src/global.json

      - name: Restore .NET dependencies
        uses: zyactions/dotnet-restore@v1
        with:
          working-directory: src/

      - name: Build solution
        run: dotnet build src/

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
