name: Test Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-code:
    name: Test Code
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Test solution
        run: dotnet test src/
